// <auto-generated />
using System;
using Auction.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Auction.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260303202847_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Auction.Domain.Entities.Auction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CurrentWinningBidId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_winning_bid_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<int>("TotalBids")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_bids");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("winner_id");

                    b.Property<Guid>("category_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EndDate")
                        .HasDatabaseName("idx_auctions_end_date");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("idx_auctions_seller");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_auctions_status");

                    b.HasIndex("category_id")
                        .HasDatabaseName("idx_auctions_category");

                    b.HasIndex("EndDate", "Status")
                        .HasDatabaseName("idx_auctions_active_ending")
                        .HasFilter("status = 'Active'");

                    b.ToTable("auctions", (string)null);
                });

            modelBuilder.Entity("Auction.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_categories_name");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9f472427-9f69-4f4c-89c5-486e16c2a891"),
                            CreatedAt = new DateTime(2026, 3, 3, 20, 28, 46, 872, DateTimeKind.Utc).AddTicks(2490),
                            Description = "Dispositivos eletrônicos e gadgets",
                            Name = "Eletrônicos",
                            Version = 0L
                        },
                        new
                        {
                            Id = new Guid("aa01d274-34ab-464f-9588-867bf4890970"),
                            CreatedAt = new DateTime(2026, 3, 3, 20, 28, 46, 872, DateTimeKind.Utc).AddTicks(6039),
                            Description = "Carros, motos e outros veículos",
                            Name = "Veículos",
                            Version = 0L
                        },
                        new
                        {
                            Id = new Guid("1a93c3db-459c-42a7-88a4-7abaf19a0afc"),
                            CreatedAt = new DateTime(2026, 3, 3, 20, 28, 46, 872, DateTimeKind.Utc).AddTicks(6047),
                            Description = "Casas, apartamentos e terrenos",
                            Name = "Imóveis",
                            Version = 0L
                        },
                        new
                        {
                            Id = new Guid("565591d9-adf8-4aaf-bdc4-9182700f12cb"),
                            CreatedAt = new DateTime(2026, 3, 3, 20, 28, 46, 872, DateTimeKind.Utc).AddTicks(6049),
                            Description = "Obras de arte e colecionáveis",
                            Name = "Arte",
                            Version = 0L
                        },
                        new
                        {
                            Id = new Guid("01c644f9-d103-4a99-91bd-0a0f73c94efd"),
                            CreatedAt = new DateTime(2026, 3, 3, 20, 28, 46, 872, DateTimeKind.Utc).AddTicks(6051),
                            Description = "Joias e pedras preciosas",
                            Name = "Joias",
                            Version = 0L
                        },
                        new
                        {
                            Id = new Guid("897943a9-5646-4354-a70e-66e4be09c71d"),
                            CreatedAt = new DateTime(2026, 3, 3, 20, 28, 46, 872, DateTimeKind.Utc).AddTicks(6054),
                            Description = "Itens antigos e vintage",
                            Name = "Antiguidades",
                            Version = 0L
                        },
                        new
                        {
                            Id = new Guid("ffe3bf02-47a8-4228-b6d7-725f75aa5fad"),
                            CreatedAt = new DateTime(2026, 3, 3, 20, 28, 46, 872, DateTimeKind.Utc).AddTicks(6076),
                            Description = "Outras categorias",
                            Name = "Outros",
                            Version = 0L
                        });
                });

            modelBuilder.Entity("Auction.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<string>("user_type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);

                    b.HasDiscriminator<string>("user_type").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Auction.Domain.Entities.CorporateEntity", b =>
                {
                    b.HasBaseType("Auction.Domain.Entities.User");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("company_name");

                    b.HasDiscriminator().HasValue("Corporate");
                });

            modelBuilder.Entity("Auction.Domain.Entities.IndividualEntity", b =>
                {
                    b.HasBaseType("Auction.Domain.Entities.User");

                    b.HasDiscriminator().HasValue("Individual");
                });

            modelBuilder.Entity("Auction.Domain.Entities.Auction", b =>
                {
                    b.HasOne("Auction.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Auction.Domain.ValueObjects.Money", "BidIncrement", b1 =>
                        {
                            b1.Property<Guid>("AuctionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("BRL")
                                .HasColumnName("bid_increment_currency");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("bid_increment_amount");

                            b1.HasKey("AuctionId");

                            b1.ToTable("auctions");

                            b1.WithOwner()
                                .HasForeignKey("AuctionId");
                        });

                    b.OwnsOne("Auction.Domain.ValueObjects.Money", "BuyNowPrice", b1 =>
                        {
                            b1.Property<Guid>("AuctionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("buy_now_price_currency");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("buy_now_price_amount");

                            b1.HasKey("AuctionId");

                            b1.ToTable("auctions");

                            b1.WithOwner()
                                .HasForeignKey("AuctionId");
                        });

                    b.OwnsOne("Auction.Domain.ValueObjects.Money", "CurrentPrice", b1 =>
                        {
                            b1.Property<Guid>("AuctionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("BRL")
                                .HasColumnName("current_price_currency");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("current_price_amount");

                            b1.HasKey("AuctionId");

                            b1.ToTable("auctions");

                            b1.WithOwner()
                                .HasForeignKey("AuctionId");
                        });

                    b.OwnsOne("Auction.Domain.ValueObjects.Money", "ReservePrice", b1 =>
                        {
                            b1.Property<Guid>("AuctionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("BRL")
                                .HasColumnName("reserve_price_currency");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("reserve_price_amount");

                            b1.HasKey("AuctionId");

                            b1.ToTable("auctions");

                            b1.WithOwner()
                                .HasForeignKey("AuctionId");
                        });

                    b.OwnsOne("Auction.Domain.ValueObjects.Money", "StartingPrice", b1 =>
                        {
                            b1.Property<Guid>("AuctionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("BRL")
                                .HasColumnName("starting_price_currency");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("starting_price_amount");

                            b1.HasKey("AuctionId");

                            b1.ToTable("auctions");

                            b1.WithOwner()
                                .HasForeignKey("AuctionId");
                        });

                    b.OwnsOne("Auction.Domain.ValueObjects.AuctionRules", "Rules", b1 =>
                        {
                            b1.Property<Guid>("AuctionId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("AllowProxyBids")
                                .HasColumnType("boolean")
                                .HasColumnName("allow_proxy_bids");

                            b1.Property<TimeSpan>("ExtensionTime")
                                .HasColumnType("interval")
                                .HasColumnName("extension_time");

                            b1.Property<TimeSpan>("ExtensionWindow")
                                .HasColumnType("interval")
                                .HasColumnName("extension_window");

                            b1.Property<int>("MaxBidsPerUser")
                                .HasColumnType("integer")
                                .HasColumnName("max_bids_per_user");

                            b1.HasKey("AuctionId");

                            b1.ToTable("auctions");

                            b1.ToJson("rules");

                            b1.WithOwner()
                                .HasForeignKey("AuctionId");
                        });

                    b.Navigation("BidIncrement")
                        .IsRequired();

                    b.Navigation("BuyNowPrice");

                    b.Navigation("Category");

                    b.Navigation("CurrentPrice")
                        .IsRequired();

                    b.Navigation("ReservePrice")
                        .IsRequired();

                    b.Navigation("Rules")
                        .IsRequired();

                    b.Navigation("StartingPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("Auction.Domain.Entities.User", b =>
                {
                    b.OwnsOne("Auction.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("idx_users_email");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Auction.Domain.ValueObjects.Password", "Password", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("HashedValue")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("password_hash");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();
                });

            modelBuilder.Entity("Auction.Domain.Entities.CorporateEntity", b =>
                {
                    b.OwnsOne("Auction.Domain.ValueObjects.Cnpj", "Cnpj", b1 =>
                        {
                            b1.Property<Guid>("CorporateEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("character varying(14)")
                                .HasColumnName("cnpj");

                            b1.HasKey("CorporateEntityId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("CorporateEntityId");
                        });

                    b.Navigation("Cnpj")
                        .IsRequired();
                });

            modelBuilder.Entity("Auction.Domain.Entities.IndividualEntity", b =>
                {
                    b.OwnsOne("Auction.Domain.ValueObjects.Cpf", "Cpf", b1 =>
                        {
                            b1.Property<Guid>("IndividualEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("cpf");

                            b1.HasKey("IndividualEntityId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("IndividualEntityId");
                        });

                    b.Navigation("Cpf")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
