// <auto-generated />
using System;
using Auction.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Auction.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260309225257_AddBidEntity")]
    partial class AddBidEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Auction.Domain.Entities.Auction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CurrentWinningBidId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_winning_bid_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<int>("TotalBids")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_bids");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("winner_id");

                    b.Property<Guid>("category_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EndDate")
                        .HasDatabaseName("idx_auctions_end_date");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("idx_auctions_seller");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_auctions_status");

                    b.HasIndex("category_id")
                        .HasDatabaseName("idx_auctions_category");

                    b.HasIndex("EndDate", "Status")
                        .HasDatabaseName("idx_auctions_active_ending")
                        .HasFilter("status = 'Active'");

                    b.ToTable("auctions", (string)null);
                });

            modelBuilder.Entity("Auction.Domain.Entities.Bid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuctionId")
                        .HasColumnType("uuid")
                        .HasColumnName("auction_id");

                    b.Property<int>("BidStatus")
                        .HasColumnType("integer")
                        .HasColumnName("bid_status");

                    b.Property<DateTime>("BidTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bid_time");

                    b.Property<Guid>("BidderId")
                        .HasColumnType("uuid")
                        .HasColumnName("bidder_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsAutoBid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_auto_bid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId")
                        .HasDatabaseName("ix_bids_auction_id");

                    b.HasIndex("BidTime")
                        .HasDatabaseName("ix_bids_bid_time");

                    b.HasIndex("BidderId")
                        .HasDatabaseName("ix_bids_bidder_id");

                    b.HasIndex("AuctionId", "BidStatus")
                        .HasDatabaseName("ix_bids_auction_status");

                    b.ToTable("bids", (string)null);
                });

            modelBuilder.Entity("Auction.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_categories_name");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("62fb8846-ac7d-481f-8b91-e19941180753"),
                            CreatedAt = new DateTime(2026, 3, 9, 22, 52, 56, 798, DateTimeKind.Utc).AddTicks(1586),
                            Description = "Dispositivos eletrônicos e gadgets",
                            Name = "Eletrônicos",
                            Version = 0L
                        },
                        new
                        {
                            Id = new Guid("448fb831-8414-4181-81dd-318b5a569194"),
                            CreatedAt = new DateTime(2026, 3, 9, 22, 52, 56, 798, DateTimeKind.Utc).AddTicks(4376),
                            Description = "Carros, motos e outros veículos",
                            Name = "Veículos",
                            Version = 0L
                        },
                        new
                        {
                            Id = new Guid("c9d47c38-d3ea-423d-a089-5ba55e14055e"),
                            CreatedAt = new DateTime(2026, 3, 9, 22, 52, 56, 798, DateTimeKind.Utc).AddTicks(4380),
                            Description = "Casas, apartamentos e terrenos",
                            Name = "Imóveis",
                            Version = 0L
                        },
                        new
                        {
                            Id = new Guid("09ede924-5eac-4ccc-88ef-bedd335ece17"),
                            CreatedAt = new DateTime(2026, 3, 9, 22, 52, 56, 798, DateTimeKind.Utc).AddTicks(4381),
                            Description = "Obras de arte e colecionáveis",
                            Name = "Arte",
                            Version = 0L
                        },
                        new
                        {
                            Id = new Guid("ddebd330-f35b-4e8f-b820-e110168be0bf"),
                            CreatedAt = new DateTime(2026, 3, 9, 22, 52, 56, 798, DateTimeKind.Utc).AddTicks(4382),
                            Description = "Joias e pedras preciosas",
                            Name = "Joias",
                            Version = 0L
                        },
                        new
                        {
                            Id = new Guid("0ec67cca-1ece-4e11-bd70-5b335774345e"),
                            CreatedAt = new DateTime(2026, 3, 9, 22, 52, 56, 798, DateTimeKind.Utc).AddTicks(4383),
                            Description = "Itens antigos e vintage",
                            Name = "Antiguidades",
                            Version = 0L
                        },
                        new
                        {
                            Id = new Guid("71b9be8f-278e-4a86-a945-61e71edd134e"),
                            CreatedAt = new DateTime(2026, 3, 9, 22, 52, 56, 798, DateTimeKind.Utc).AddTicks(4384),
                            Description = "Outras categorias",
                            Name = "Outros",
                            Version = 0L
                        });
                });

            modelBuilder.Entity("Auction.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<string>("user_type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);

                    b.HasDiscriminator<string>("user_type").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Auction.Domain.Entities.CorporateEntity", b =>
                {
                    b.HasBaseType("Auction.Domain.Entities.User");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("company_name");

                    b.HasDiscriminator().HasValue("Corporate");
                });

            modelBuilder.Entity("Auction.Domain.Entities.IndividualEntity", b =>
                {
                    b.HasBaseType("Auction.Domain.Entities.User");

                    b.HasDiscriminator().HasValue("Individual");
                });

            modelBuilder.Entity("Auction.Domain.Entities.Auction", b =>
                {
                    b.HasOne("Auction.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Auction.Domain.ValueObjects.Money", "BidIncrement", b1 =>
                        {
                            b1.Property<Guid>("AuctionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("BRL")
                                .HasColumnName("bid_increment_currency");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("bid_increment_amount");

                            b1.HasKey("AuctionId");

                            b1.ToTable("auctions");

                            b1.WithOwner()
                                .HasForeignKey("AuctionId");
                        });

                    b.OwnsOne("Auction.Domain.ValueObjects.Money", "BuyNowPrice", b1 =>
                        {
                            b1.Property<Guid>("AuctionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("buy_now_price_currency");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("buy_now_price_amount");

                            b1.HasKey("AuctionId");

                            b1.ToTable("auctions");

                            b1.WithOwner()
                                .HasForeignKey("AuctionId");
                        });

                    b.OwnsOne("Auction.Domain.ValueObjects.Money", "CurrentPrice", b1 =>
                        {
                            b1.Property<Guid>("AuctionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("BRL")
                                .HasColumnName("current_price_currency");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("current_price_amount");

                            b1.HasKey("AuctionId");

                            b1.ToTable("auctions");

                            b1.WithOwner()
                                .HasForeignKey("AuctionId");
                        });

                    b.OwnsOne("Auction.Domain.ValueObjects.Money", "ReservePrice", b1 =>
                        {
                            b1.Property<Guid>("AuctionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("BRL")
                                .HasColumnName("reserve_price_currency");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("reserve_price_amount");

                            b1.HasKey("AuctionId");

                            b1.ToTable("auctions");

                            b1.WithOwner()
                                .HasForeignKey("AuctionId");
                        });

                    b.OwnsOne("Auction.Domain.ValueObjects.Money", "StartingPrice", b1 =>
                        {
                            b1.Property<Guid>("AuctionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("BRL")
                                .HasColumnName("starting_price_currency");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("starting_price_amount");

                            b1.HasKey("AuctionId");

                            b1.ToTable("auctions");

                            b1.WithOwner()
                                .HasForeignKey("AuctionId");
                        });

                    b.OwnsOne("Auction.Domain.ValueObjects.AuctionRules", "Rules", b1 =>
                        {
                            b1.Property<Guid>("AuctionId");

                            b1.Property<bool>("AllowProxyBids");

                            b1.Property<TimeSpan>("ExtensionTime");

                            b1.Property<TimeSpan>("ExtensionWindow");

                            b1.Property<int>("MaxBidsPerUser");

                            b1.HasKey("AuctionId");

                            b1.ToTable("auctions");

                            b1
                                .ToJson("rules")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("AuctionId");
                        });

                    b.Navigation("BidIncrement")
                        .IsRequired();

                    b.Navigation("BuyNowPrice");

                    b.Navigation("Category");

                    b.Navigation("CurrentPrice")
                        .IsRequired();

                    b.Navigation("ReservePrice")
                        .IsRequired();

                    b.Navigation("Rules")
                        .IsRequired();

                    b.Navigation("StartingPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("Auction.Domain.Entities.Bid", b =>
                {
                    b.HasOne("Auction.Domain.Entities.Auction", null)
                        .WithMany()
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auction.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("BidderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Auction.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("BidId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("amount");

                            b1.HasKey("BidId");

                            b1.ToTable("bids");

                            b1.WithOwner()
                                .HasForeignKey("BidId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("Auction.Domain.Entities.User", b =>
                {
                    b.OwnsOne("Auction.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("idx_users_email");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Auction.Domain.ValueObjects.Password", "Password", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("HashedValue")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("password_hash");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();
                });

            modelBuilder.Entity("Auction.Domain.Entities.CorporateEntity", b =>
                {
                    b.OwnsOne("Auction.Domain.ValueObjects.Cnpj", "Cnpj", b1 =>
                        {
                            b1.Property<Guid>("CorporateEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("character varying(14)")
                                .HasColumnName("cnpj");

                            b1.HasKey("CorporateEntityId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("CorporateEntityId");
                        });

                    b.Navigation("Cnpj")
                        .IsRequired();
                });

            modelBuilder.Entity("Auction.Domain.Entities.IndividualEntity", b =>
                {
                    b.OwnsOne("Auction.Domain.ValueObjects.Cpf", "Cpf", b1 =>
                        {
                            b1.Property<Guid>("IndividualEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("cpf");

                            b1.HasKey("IndividualEntityId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("IndividualEntityId");
                        });

                    b.Navigation("Cpf")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
